### ISSUE TITLE
Check out the best way to connect postgres with nextjs backend

### ISSUE THREAD

**Issue by viriatonova** [capaolab/grama#5]
### Description

We need to decide the best aproche to handle database connections with using NextJs in backend

**Comment by viriatonova** [comment]
@Rodrigo-Dev123 Ao que tudo indica a melhor solução para fazer backend em Nextjs é o [Prisma](https://www.prisma.io/). Um artigo da Versel sobre como fazer fullstack app com Next e Prisma ->  [Artigo do Next sobre Prisma](https://vercel.com/guides/nextjs-prisma-postgres). 

Dá uma olhada ai e vẽ se você chega a outra conclusão.

**Comment by Rodrigo-Dev123** [comment]
@viriatonova Eu também concordo que o Prisma seja o melhor ORM para o projeto já que ele é simples, prático e muito popular assim como mostra o [npm trends](https://npmtrends.com/prisma-vs-sequelize-vs-typeorm), eu fiz o projeto deste [turorial](https://youtu.be/mikoTbhH_Qg?si=vG6FHGK8kofEoEw4) usando o Nextjs e Prisma e achei muito bom a maneira de implementar.
