### ISSUE TITLE
Checkout the best way to handle auth

### ISSUE THREAD

**Issue by viriatonova** [capaolab/grama#6]
### Description

We need to research the best aproches to handle authentication and permissions in a full stack project using NextJS

**Comment by viriatonova** [comment]
@Rodrigo-Dev123 Começando aqui as pesquisas. Tu havia comentado no outro projeto que tinha alguns problemas com React Hook Form. Estou pesquisando sobre auth e validação de formulário, tanto no front quanto no back é uma questão a se considerar logo. Podemos seguir com React Hook Form? 

Um dos ponto que isso toca é na escolha da lib de validação. Como não vamos usar typescript estou tendencioso a usar o [Yup](https://www.npmjs.com/package/yup/v/1.0.0-alpha.3) e o a libre React Hook Form já tem integração direta, por isso estou levantando essa questão

**Comment by Rodrigo-Dev123** [comment]
O React Hook Form é uma lib muito boa, o principal problema em questão era a parte da componentização dos campos do formulário que nós não tinhamos conseguido fazer porque dava erro na hora de passar o objeto `{ ...register }` como prop, enquanto o outro problema dos valores default nos inputs eu consegui resolver usando a função setValue() da própria lib.

**Comment by Rodrigo-Dev123** [comment]
Eu vou pesquisar melhor sobre isso, talvez tenha alguma forma específica de componentizar usando o React Hook Form.

**Comment by Rodrigo-Dev123** [comment]
@viriatonova achei este [blog](https://jujuontheweb.medium.com/how-to-use-react-hook-form-with-your-custom-form-components-a86a1a77cf3c) que ensina a usar o React Hook Form com componente personalizado se isto resolver o problema, eu digo que podemos seguir com esta lib mesmo já que ela é muito boa.

**Comment by viriatonova** [comment]
@Rodrigo-Dev123 Resumo da funcionalidade até o momento:

1. [React Hook Form](https://react-hook-form.com/) para validação na UI
2. [Yup](https://www.npmjs.com/package/yup/v/1.0.0-alpha.3) para validação de schema no backend

Agora precisamos resolver a arquitetura da autenticação. Uma vez que vamos ter um sistema monolito podemos pensar em não usar a estratégia de refresh token criando um sistema de auth, permissão e sessão no Next (ou usar um pronto). Se entendermos que a forma mais segura é usar o esquema de refresh token então temos que organizar a arquitetura.

**Comment by viriatonova** [comment]
@Rodrigo-Dev123 Esse artigo :point_right: [Authentication](https://nextjs.org/docs/app/building-your-application/authentication) no Next me parece um bom começo para autenticação. Vou fechar essa issue considerando que já chegamos no final e abrir uma para implementar o modelo de autenticação descrito no artigo.
